### ISSUE TITLE
Segfaults when compiled with `-march=native`

### ISSUE THREAD

**Issue by gotzl** [ROCm-Developer-Tools/clr#31]
ROCm: 5.7.1
gcc (Gentoo 13.2.1_p20230826 p7) 13.2.1 20230826
Linux desktop 6.6.0-pf2 #1 SMP PREEMPT_DYNAMIC
AMD Ryzen 9 5900X + 7900XTX

When I compile with `-march=native`, I get a segfaults in OpenCL and HIP applications. For example, when I run `./ocltst -m liboclperf.so` I get the following trace:
```
(gdb) bt
#0  _mm256_stream_si256 (__B=..., __A=<optimized out>) at /var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/rocclr/device/rocm/rocvirtual.cpp:2807
#1  roc::nontemporalMemcpy (size=96, src=0x55c4f440bdb0, dst=0x7f0985600000) at /var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/rocclr/device/rocm/rocvirtual.cpp:2807
#2  roc::VirtualGPU::submitKernelInternal (this=this@entry=0x7f0994000c70, sizes=..., kernel=..., parameters=<optimized out>, eventHandle=eventHandle@entry=0x55c4f4063ad0, sharedMemBytes=<optimized out>, vcmd=<optimized out>, aql_packet=<optimized out>)
    at /var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/rocclr/device/rocm/rocvirtual.cpp:3099
#3  0x00007f0aa4d646bc in roc::VirtualGPU::submitKernel (this=0x7f0994000c70, vcmd=...) at /var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/rocclr/device/rocm/rocvirtual.cpp:3278
#4  0x00007f0aa4d248dc in amd::HostQueue::loop (this=this@entry=0x55c4f3ed83e0, virtualDevice=0x7f0994000c70) at /var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/rocclr/platform/commandqueue.cpp:217
#5  0x00007f0aa4d25f0b in amd::HostQueue::Thread::run (this=0x55c4f3ed8508, data=0x55c4f3ed83e0) at /var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/rocclr/platform/commandqueue.hpp:172
#6  0x00007f0aa4cb493d in amd::Thread::main (this=this@entry=0x55c4f3ed8508) at /var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/rocclr/thread/thread.cpp:93
#7  0x00007f0aa4d18422 in amd::Thread::entry (thread=0x55c4f3ed8508) at /var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/rocclr/os/os_posix.cpp:340
#8  0x00007f0aa4ead2b9 in ?? () from /usr/lib64/libc.so.6
#9  0x00007f0aa4f3030c in ?? () from /usr/lib64/libc.so.6
```
If I remove `-march=native`, everything works fine.

A typical compilation line that produces the segfault looks like this
```
[82/107] /usr/bin/x86_64-pc-linux-gnu-g++ -DATI_OS_LINUX -DCL_TARGET_OPENCL_VERSION=220 -DCL_USE_DEPRECATED_OPENCL_1_0_APIS -DCL_USE_DEPRECATED_OPENCL_1_1_APIS -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_USE_DEPRECATED_OPENCL_2_0_APIS -DCOMGR_DYN_DLL -DHAVE_CL2_HPP -DLITTLEENDIAN_CPU -DOPENCL_C_MAJOR=2 -DOPENCL_C_MINOR=0 -DOPENCL_MAJOR=2 -DOPENCL_MINOR=1 -DROCCLR_SUPPORT_NUMA_POLICY -DUSE_COMGR_LIBRARY -DWITH_HSA_DEVICE -DWITH_LIGHTNING_COMPILER -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/rocclr -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/rocclr/compiler/lib -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/rocclr/compiler/lib/include -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/rocclr/compiler/lib/backends/common -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/rocclr/device -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/rocclr/elf -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/rocclr/include -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/opencl/khronos/headers/opencl2.2/CL -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/opencl/khronos/headers/opencl2.2/CL/.. -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/opencl/khronos/headers/opencl2.2/CL/../.. -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/opencl/khronos/headers/opencl2.2/CL/../../.. -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/opencl/khronos/headers/opencl2.2/CL/../../../.. -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/opencl/khronos/headers/opencl2.2/CL/../../../../amdocl  -march=native -O2 -pipe -std=c++17 -fPIC -MD -MT rocclr/CMakeFiles/rocclr.dir/device/rocm/rocvirtual.cpp.o -MF rocclr/CMakeFiles/rocclr.dir/device/rocm/rocvirtual.cpp.o.d -o rocclr/CMakeFiles/rocclr.dir/device/rocm/rocvirtual.cpp.o -c /var/tmp/portage/dev-libs/rocm-opencl-runtime-5.7.1/work/clr-rocm-5.7.1/rocclr/device/rocm/rocvirtual.cpp
```
Flags selected by `-march=native`:
```
$ gcc -march=native -E -v - </dev/null 2>&1 | grep cc1
 /usr/libexec/gcc/x86_64-pc-linux-gnu/13/cc1 -E -quiet -v - -march=znver3 -mmmx -mpopcnt -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mavx2 -msse4a -mno-fma4 -mno-xop -mfma -mno-avx512f -mbmi -mbmi2 -maes -mpclmul -mno-avx512vl -mno-avx512bw -mno-avx512dq -mno-avx512cd -mno-avx512er -mno-avx512pf -mno-avx512vbmi -mno-avx512ifma -mno-avx5124vnniw -mno-avx5124fmaps -mno-avx512vpopcntdq -mno-avx512vbmi2 -mno-gfni -mvpclmulqdq -mno-avx512vnni -mno-avx512bitalg -mno-avx512bf16 -mno-avx512vp2intersect -mno-3dnow -madx -mabm -mno-cldemote -mclflushopt -mclwb -mclzero -mcx16 -mno-enqcmd -mf16c -mfsgsbase -mfxsr -mno-hle -msahf -mno-lwp -mlzcnt -mmovbe -mno-movdir64b -mno-movdiri -mmwaitx -mno-pconfig -mpku -mno-prefetchwt1 -mprfchw -mno-ptwrite -mrdpid -mrdrnd -mrdseed -mno-rtm -mno-serialize -mno-sgx -msha -mshstk -mno-tbm -mno-tsxldtrk -mvaes -mno-waitpkg -mwbnoinvd -mxsave -mxsavec -mxsaveopt -mxsaves -mno-amx-tile -mno-amx-int8 -mno-amx-bf16 -mno-uintr -mno-hreset -mno-kl -mno-widekl -mno-avxvnni -mno-avx512fp16 -mno-avxifma -mno-avxvnniint8 -mno-avxneconvert -mno-cmpccxadd -mno-amx-fp16 -mno-prefetchi -mno-raoint -mno-amx-complex --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=512 -mtune=znver3 -dumpbase -
```

**Comment by gotzl** [comment]
Closing as this is a dup of #18 (although I report it here for the opencl runtime)
